'use client';

import React from 'react';
import Head from 'next/head';

const PrivacyPolicyPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy | Magica</title>
        <meta name="description" content="Read our privacy policy to learn how we protect your data." />
      </Head>

      <main className="px-6 md:px-24 py-12 bg-black text-white">
        <h1 className="text-4xl font-extrabold mb-4 text-purple-400">Privacy Policy</h1>
        <p className="mb-4 text-sm text-gray-400">Last updated: May 26, 2025</p>

        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>

        <p className="mb-4">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
          collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the{' '}
          <a
            href="https://www.termsfeed.com/privacy-policy-generator/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-400 hover:underline"
          >
            Privacy Policy Generator
          </a>
          .
        </p>

        <h2 className="text-2xl font-bold mt-10 mb-3 text-purple-300">Interpretation and Definitions</h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings defined under the following conditions.
          The following definitions shall have the same meaning regardless of whether they appear in singular or in
          plural.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
        <p className="mb-2">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 text-gray-300">
          <li><strong>Account:</strong> A unique account created for You to access our Service.</li>
          <li><strong>Affiliate:</strong> An entity that controls, is controlled by or is under common control with a party.</li>
          <li><strong>Company:</strong> Refers to Magica.</li>
          <li><strong>Cookies:</strong> Small files placed on Your device by a website.</li>
          <li><strong>Country:</strong> Refers to: Uttar Pradesh, India.</li>
          <li><strong>Device:</strong> Any device that can access the Service such as a computer, cellphone or tablet.</li>
          <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service:</strong> Refers to the Website.</li>
          <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Third-party Social Media Service:</strong> Any website or social network through which a User can log in.</li>
          <li><strong>Usage Data:</strong> Data collected automatically generated by using the Service.</li>
          <li>
            <strong>Website:</strong> Refers to Magica, accessible from{' '}
            <a
              href="https://my-blog-platform-fqtv.vercel.app/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 hover:underline"
            >
              https://my-blog-platform-fqtv.vercel.app/
            </a>
          </li>
          <li><strong>You:</strong> The individual accessing or using the Service.</li>
        </ul>

        <h2 className="text-2xl font-bold mt-10 mb-3 text-purple-300">Collecting and Using Your Personal Data</h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">Types of Data Collected</h3>
        <h4 className="text-lg font-semibold mt-4">Personal Data</h4>
        <p className="mb-2">While using Our Service, We may ask You to provide:</p>
        <ul className="list-disc list-inside mb-6 text-gray-300">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-semibold mt-4">Usage Data</h4>
        <p className="mb-4">Usage Data is collected automatically when using the Service...</p>

        <h4 className="text-lg font-semibold mt-4">Information from Third-Party Social Media Services</h4>
        <ul className="list-disc list-inside mb-4 text-gray-300">
          <li>Google</li>
          <li>Facebook</li>
          <li>Instagram</li>
          <li>Twitter</li>
          <li>LinkedIn</li>
        </ul>
        <p className="mb-6">If You decide to register through or grant access to a Third-Party Social Media Service...</p>

        <h4 className="text-lg font-semibold mt-4">Tracking Technologies and Cookies</h4>
        <p className="mb-2">We use Cookies and similar tracking technologies to track activity...</p>
        <ul className="list-disc list-inside mb-6 text-gray-300">
          <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device.</li>
          <li><strong>Web Beacons:</strong> Small electronic files used to count users or understand interaction.</li>
        </ul>

        <p className="mb-4">
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.{' '}
          <a
            href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-400 hover:underline"
          >
            Learn more here
          </a>
        </p>

        <ul className="list-disc list-inside mb-8 text-gray-300">
          <li><strong>Necessary / Essential Cookies:</strong> Session cookies used for authentication.</li>
          <li><strong>Notice Acceptance Cookies:</strong> Persistent cookies to check cookie consent.</li>
          <li><strong>Functionality Cookies:</strong> Used to remember preferences.</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-2">Use of Your Personal Data</h3>
        <ul className="list-disc list-inside mb-6 text-gray-300">
          <li>To provide and maintain our Service</li>
          <li>To manage Your Account</li>
          <li>For the performance of a contract</li>
          <li>To contact You</li>
          <li>To provide news, updates, and offers</li>
          <li>To manage Your requests</li>
          <li>For business transfers</li>
          <li>For analytics and service improvement</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-2">Sharing Your Personal Information</h3>
        <ul className="list-disc list-inside mb-6 text-gray-300">
          <li>With Service Providers</li>
          <li>For business transfers</li>
          <li>With Affiliates</li>
          <li>With Business Partners</li>
          <li>With Other Users</li>
          <li>With Your consent</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-2">Retention and Transfer of Your Personal Data</h3>
        <p className="mb-4">We retain Your Personal Data only as long as necessary. Your data may be processed outside of Your country.</p>

        <p className="text-sm text-gray-500 mt-12">© 2025 Magica. All rights reserved.</p>
      </main>
    </>
  );
};

export default PrivacyPolicyPage;
